# Generated by Django 2.0.2 on 2018-08-08 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('lastNameP', models.CharField(blank=True, max_length=25)),
                ('lastNameM', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(max_length=35, unique=True)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('type_account', models.CharField(choices=[('Seleccion', 'Seleccione Tipo de Cuenta'), ('Captura', 'Captura'), ('Operativo', 'Operativo'), ('Administrador', 'Administrador')], default='Seleccion', max_length=13)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateField(blank=True, max_length=6)),
                ('date_born', models.DateField(blank=True, max_length=6)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id_authority', models.AutoField(primary_key=True, serialize=False)),
                ('name_authority', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('Primera Instancia y Menores', 'Primera Instancia y Menores'), ('Septimo Circuito', 'Septimo Circuito'), ('Otros...', 'Otros...')], default='Seleccion', max_length=30)),
                ('city', models.CharField(choices=[('Seleccion', 'Selecciona un elemento'), ('XALAPA', 'Xalapa'), ('VERACRUZ', 'Veracruz'), ('POZA RICA', 'Poza Rica'), ('OTROS...', 'Otros...')], default='Seleccion', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'autoridad',
                'verbose_name_plural': 'autoridades',
                'db_table': 'authority',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('name_person', models.CharField(max_length=100)),
                ('num_folio', models.CharField(max_length=8)),
                ('consecutive', models.CharField(max_length=4)),
                ('num_folio_anwser', models.IntegerField(blank=True, null=True, unique=True)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sco.Authority')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id_process', models.AutoField(primary_key=True, serialize=False)),
                ('manager_process', models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('Lic. Olivia', 'Lic. Olivia'), ('Lic. Yair', 'Lic. Yair'), ('Lic. Abad', 'Lic. Abad')], default='Seleccion', max_length=100)),
                ('derivate_area', models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('Area Afiliacón', 'Area Afiliación'), ('Area Personal', 'Area Personal'), ('Area Prestaciones Economicas', 'Area Prestaciones Economicas'), ('Area Retiro Laboral', 'Area Retiro Laboral'), ('Area Medica', 'Area Medica'), ('Otros', 'Otros')], default='Seleccion', max_length=100)),
                ('status', models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('Turnado', 'Turnado'), ('Turnado/Area', 'Turnado/Area'), ('Respuesta/Area', 'Respuesta/Area'), ('Enviado/Autoridad', 'Enviado/Autoridad')], default='Seleccion', max_length=100)),
                ('date_delivery', models.DateField(blank=True, max_length=6, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'proceso',
                'verbose_name_plural': 'procesos',
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('Asuntos_Administrativos', 'Asuntos Administrativos'), ('Asuntos_Civiles', 'Asuntos Civiles'), ('Asuntos_Penales', 'Asuntos Penales'), ('Depositaria_Infiel', 'Depositaria Infiel'), ('Expedientes_Penales', 'Expedientes Penales'), ('Informes_Autoridad', 'Informes Autoridad'), ('Juicios_Amparo', 'Juicios Amparo'), ('Juicios_Civiles', 'Juicios Civiles'), ('Negativa_Peritos', 'Negativa Peritos'), ('Oficios_Varios', 'Oficios Varios'), ('Pensiones_Alimenticias', 'Pensiones Alimenticias'), ('Recuperacion_Fianzas', 'Recuperación Fianzas')], default='Seleccion', max_length=30)),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('document_answer', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tipo',
                'verbose_name_plural': 'tipos',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Type_InformeA',
            fields=[
                ('id_type_informe', models.AutoField(primary_key=True, serialize=False)),
                ('date_redaction', models.DateTimeField(blank=True, max_length=6, null=True)),
                ('document_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_control', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'informe_autoridad',
                'verbose_name_plural': 'informes_autoridad',
                'db_table': 'type_informe_a',
            },
        ),
        migrations.CreateModel(
            name='Type_Pension',
            fields=[
                ('id_pension', models.AutoField(primary_key=True, serialize=False)),
                ('ordinary_judg', models.CharField(max_length=14)),
                ('beneficiary', models.CharField(max_length=80)),
                ('disposition_type', models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('PROVISIONAL', 'Provisional'), ('DEFINITIVO', 'Definitivo')], default='Seleccion', max_length=30)),
                ('date_efect', models.DateField(blank=True, max_length=10, null=True)),
                ('pension_type', models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('Inclusión', 'Inclusión'), ('Modificación', 'Modificación'), ('Cancelación', 'Cancelación')], default='Seleccion', max_length=30)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tipo_pension',
                'verbose_name_plural': 'tipo_pensiones',
                'db_table': 'type_pension',
            },
        ),
        migrations.AddField(
            model_name='type',
            name='informeA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sco.Type_InformeA'),
        ),
        migrations.AddField(
            model_name='type',
            name='pension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sco.Type_Pension'),
        ),
        migrations.AddField(
            model_name='document',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sco.Process'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sco.Type'),
        ),
    ]
