# Generated by Django 2.0.2 on 2018-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='category',
            field=models.CharField(choices=[('Seleccion', 'Seleccione un elemento'), ('PRIMERA INSTANCIA Y MENORES', 'Primera Instancia y Menores'), ('SEPTIMO CIRCUITO', 'Septimo Circuito'), ('OTROS...', 'Otros...')], default='Seleccion', max_length=30),
        ),
        migrations.AlterField(
            model_name='type_pension',
            name='pension_type',
            field=models.CharField(max_length=30),
        ),
    ]
