"""
Django settings for contencioso project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'op7s2ys3-@q@-*pt2k10@05a6#++k&ut1ljrc!08_d9zrg95dn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sco',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #middleware for authenticad user
    #'contencioso.middleware.LoginRequiredMiddleware'

]

ROOT_URLCONF = 'contencioso.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')

WSGI_APPLICATION = 'contencioso.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '~/my.cnf',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'es'
_ = lambda s: s
LANGUAGES = (
 ('es', _('Espanish')),
 ('en', _('English')),
)

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


#STATICFILES_DIRS = (
#    os.path.join(BASE_DIR, 'stat'),
#)

STATIC_ROOT = os.path.join(BASE_DIR, '/home/crisantru/Documentos/servicio_social/contencioso/sco/static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, '/home/crisantru/Documentos/servicio_social/contencioso/media')
MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/sco/'
LOGIN_URL = '/sco/login/'

LOGIN_EXEMPT_URLS = {
    #r'^sco/login/$',
    r'^sco/logout/$',
    #r'^sco/register/$',
}


AUTH_USER_MODEL = 'sco.User'
AUTHENTICATION_BACKENDS = ('sco.backends.CustomUserAuthentication', )
#ALLOWED_HOSTS = ['192.168.0.119', 'localhost', '127.0.0.1']

#files for consecutive num for special categories
FILE_NUM_RESPUESTA = '/num_oficio_res.txt'
FILE_NUM_INFORME = '/control_interno.txt'
